-- Project Capstone_1
-- Student Ndifon Caleb Ndakina
-- Sales Manager Jim Heck
-- Sales Terrtory Colorado-west reion

USE sample_sales;
-- q4
-- Confirming jim heck sale territory

-- Interpretation
-- This query checks the management table to confirm which state and region are assigned to Sales Manager Jim Heck. 
-- It filters the records where the SalesManager is Jim Heck

SELECT SalesManager, Region, State
FROM  management
WHERE SalesManager = 'Jim Heck';
 
-- ∗ What is total revenue overall for sales in the assigned territory, plus the start date and end date that tell you what period the data covers? 

-- Interpretation
-- Interpretatio This query calculates the total in-store revenue for Jim Heck’s territory using SUM.
-- It joins sales, store locations, and management tables so the sales can be connected to Colorado using the salemanager.
-- It also finds the earliest and latest transaction dates using MIM, MAX.

SELECT m.SalesManager, m.State AS Territory, m.Region,
SUM(ss.Sale_Amount) AS Total_Revenue,
MIN(ss.Transaction_Date) AS Start_Date,
MAX(ss.Transaction_Date) AS End_Date
FROM Store_Sales ss
JOIN Store_Locations sl
ON ss.Store_ID = sl.Store_Id
JOIN Management m
ON sl.State = m.State
WHERE m.SalesManager = 'Jim Heck'
GROUP BY m.SalesManager, m.State, m.Region;

-- The result shows that the West region Colorado produces a total revenue of 6412632.22 Between January 2022 two December 31, 2025


-- ∗ What is the month by month revenue breakdown for the sales territory?

-- Interpretation
-- This query groups Jim Heck Colorado sales by month.
-- It uses DATE_FORMAT to change each transaction date into a year-month format, 
-- then calculates the total revenue for each month using SUM.

SELECT m.SalesManager, m.State AS Territory,
DATE_FORMAT(ss.Transaction_Date, '%Y-%m') AS Sales_Month,
SUM(ss.Sale_Amount) AS Monthly_Revenue
FROM Store_Sales ss
JOIN Store_Locations sl
ON ss.Store_ID = sl.Store_Id
JOIN Management m
ON sl.State = m.State
WHERE m.SalesManager = 'Jim Heck'
GROUP BY m.SalesManager, m.State,
DATE_FORMAT(ss.Transaction_Date, '%Y-%m')
ORDER BY Sales_Month;

-- ∗ Provide a comparison of total revenue for the specific sales territory and the region it belongs to
-- west revenue Instore

-- Interpretation
-- The first query calculates total in-store revenue for the entire West regionusing SumSale_Amount 
-- The second query calculates online revenue from Colorado.by SUM Salestotal
-- The third query calculates total in-store revenue only for Jim Heck’s Colorado territory.
-- Together, these queries help compare Jim Heck territory revenue agains the West region and Colorado online sales.

SELECT SUM(s.Sale_Amount) AS Total_Revenue
FROM Store_Sales s
JOIN Store_Locations l
ON s.Store_ID = l.Store_Id
JOIN Management m
ON l.State = m.State
WHERE m.Region = 'West';

-- Oline
SELECT SUM(SalesTotal) AS Online_Revenue
FROM Online_Sales
WHERE ShiptoState = 'Colorado';


-- revenue generated by Jim Hech
SELECT SUM(s.Sale_Amount) AS Total_Revenue
FROM Store_Sales s
JOIN Store_Locations l
ON s.Store_ID = l.Store_Id
JOIN Management m
ON l.State = m.State
WHERE m.SalesManager = 'Jim Heck';

-- ∗ What is the number of transactions per month and average transaction size by product category for the sales territory

-- Interpretation
-- This query uses DATE_FORMAT to show transaction per month
-- It COUNT the number of transactions, calculates the average sale , 
-- calculates total revenue for each category by month.

SELECT DATE_FORMAT(s.Transaction_Date, '%Y-%m') AS Sales_Month, c.Category,
COUNT(*) AS Number_Of_Transactions,
AVG(s.Sale_Amount) AS Average_Transaction_Size,
SUM(s.Sale_Amount) AS Total_Revenue
FROM Store_Sales s
JOIN Store_Locations l
ON s.Store_ID = l.Store_Id
JOIN Management m
ON l.State = m.State
JOIN Products p
ON s.Prod_Num = p.ProdNum
JOIN Inventory_Categories c
ON p.Categoryid = c.Categoryid
WHERE m.SalesManager = 'Jim Heck'
GROUP BY DATE_FORMAT(s.Transaction_Date, '%Y-%m'), c.Category
ORDER BY Sales_Month, Total_Revenue DESC;

-- This shows the performance of each product category per month and the revevue it contrebute

-- * Can you provide a ranking of in-store sales performance by each store in the sales territory, or a ranking of online sales performance by state within an online sales territory

-- It counts transactions, sums total sales, and uses the RANK() function to show which store performed best.
-- Only for stores managed by Jimm Heck 


SELECT l.Store_Id, l.StoreLocation, l.State,
COUNT(*) AS Number_Of_Transactions,
SUM(s.Sale_Amount) AS Total_Revenue,
RANK() OVER (ORDER BY SUM(s.Sale_Amount) DESC) AS Store_Revenue_Rank
FROM Store_Locations l
JOIN store_sales s 
ON s.Store_ID = l.Store_Id
JOIN Management m
ON l.State = m.State
WHERE m.SalesManager = 'Jim Heck'
GROUP BY l.Store_Id, l.StoreLocation, l.State
ORDER BY Store_Revenue_Rank;

-- Online Ranking for colorado

SELECT ShiptoState,
SUM(SalesTotal) AS Total_Revenue
FROM Online_Sales
WHERE ShiptoState = 'Colorado'
GROUP BY ShiptoState
ORDER BY Total_Revenue DESC;

-- ∗ What is your recommendation for where to focus sales attention in the next quarter

-- Based on the above analysis, the store that generated the highest revenue in Colorado is Denver with the highest number of transactions.
-- This indicate that they have more customer and if provided more resources, they can generate a lot more revenue.
-- Also, the least revenue generating store in Colorado is Parker with the lowest transaction number. Which shows that they have a small population, hence not enough customer. 
-- So my recommendation is that more resources should be deployed to the stores that are bringing more return and then also focusing on developing and increasing the market of those stores that are bringing in less revenue in return.

