-- Project Capstone_1
-- Student Ndifon Caleb Ndakina
-- Sales Manager Jim Heck
-- Sales Terrtory Colorado-west reion

USE sample_sales;
-- q4
-- Confirming jim heck sale territory

SELECT SalesManager, Region, State
FROM  management
WHERE SalesManager = 'Jim Heck';
 
-- ∗ What is total revenue overall for sales in the assigned territory, plus the start date and end date that tell you what period the data covers?

SELECT m.SalesManager, m.State AS Territory, m.Region,
SUM(ss.Sale_Amount) AS Total_Revenue,
MIN(ss.Transaction_Date) AS Start_Date,
MAX(ss.Transaction_Date) AS End_Date
FROM Store_Sales ss
JOIN Store_Locations sl
ON ss.Store_ID = sl.StoreId
JOIN Management AS m
ON sl.State = m.State
WHERE m.SalesManager = 'Jim Heck'
GROUP BY m.SalesManager, m.State, m.Region;

-- The result shows that the West region Colorado produces a total revenue of 6412632.22 Between January 2022 two December 31, 2025


-- ∗ What is the month by month revenue breakdown for the sales territory?

SELECT m.SalesManager, m.State AS Territory,
    DATE_FORMAT(ss.Transaction_Date, '%Y-%m') AS Sales_Month,
    SUM(ss.Sale_Amount) AS Monthly_Revenue
FROM Store_Sales ss
JOIN Store_Locations sl
    ON ss.Store_ID = sl.StoreId
JOIN Management m
    ON sl.State = m.State
WHERE m.SalesManager = 'Jim Heck'
GROUP BY m.SalesManager, m.State,
    DATE_FORMAT(ss.Transaction_Date, '%Y-%m')
ORDER BY Sales_Month;

-- ∗ Provide a comparison of total revenue for the specific sales territory and the region it belongs to
-- west revenue Instore
SELECT SUM(s.Sale_Amount) AS Total_Revenue
FROM Store_Sales s
JOIN Store_Locations l
    ON s.Store_ID = l.Store_Id
JOIN Management m
    ON l.State = m.State
WHERE m.Region = 'West';

-- Oline
SELECT 
    SUM(SalesTotal) AS Online_Revenue
FROM Online_Sales
WHERE ShiptoState = 'Colorado';


-- revenue generated by Jim Hech
SELECT 
    SUM(s.Sale_Amount) AS Total_Revenue
FROM Store_Sales s
JOIN Store_Locations l
    ON s.Store_ID = l.Store_Id
JOIN Management m
    ON l.State = m.State
WHERE m.SalesManager = 'Jim Heck';

-- ∗ What is the number of transactions per month and average transaction size by product category for the sales territory

SELECT DATE_FORMAT(s.Transaction_Date, '%Y-%m') AS Sales_Month, c.Category,
    COUNT(*) AS Number_Of_Transactions,
    AVG(s.Sale_Amount) AS Average_Transaction_Size,
    SUM(s.Sale_Amount) AS Total_Revenue
FROM Store_Sales s
JOIN Store_Locations l
    ON s.Store_ID = l.Store_Id
JOIN Management m
    ON l.State = m.State
JOIN Products p
    ON s.Prod_Num = p.ProdNum
JOIN Inventory_Categories c
    ON p.Categoryid = c.Categoryid
WHERE m.SalesManager = 'Jim Heck'
GROUP BY
    DATE_FORMAT(s.Transaction_Date, '%Y-%m'),
    c.Category
ORDER BY Sales_Month, Total_Revenue DESC;

-- This shows the performance of each product category per month and the revevue it contrebute

-- Can you provide a ranking of in-store sales performance by each store in the sales territory, or a ranking of online sales performance by state within an online sales territory

SELECT l.Store_Id, l.StoreLocation, l.State,
    COUNT(*) AS Number_Of_Transactions,
    SUM(s.Sale_Amount) AS Total_Revenue,
    RANK() OVER (ORDER BY SUM(s.Sale_Amount) DESC) AS Store_Revenue_Rank
FROM Store_Locations l
JOIN store_sales s 
    ON s.Store_ID = l.Store_Id
JOIN Management m
    ON l.State = m.State
WHERE m.SalesManager = 'Jim Heck'
GROUP BY l.Store_Id, l.StoreLocation, l.State
ORDER BY Store_Revenue_Rank;

-- Online Ranking

SELECT ShiptoState,
SUM(SalesTotal) AS Total_Revenue
FROM Online_Sales
WHERE ShiptoState = 'Colorado'
GROUP BY ShiptoState
ORDER BY Total_Revenue DESC;

-- ∗ What is your recommendation for where to focus sales attention in the next quarter

-- Based on the above analysis, the store that generated the highest revenue in Colorado is Denver with the highest number of transactions.
-- This indicate that they have more customer and if provided more resources, they can generate a lot more revenue.
-- Also, the least revenue generating store in Colorado is Parker with the lowest transaction number. Which shows that they have a small population, hence not enough customer. 
-- So my recommendation is that more resources should be deployed to the stores that are bringing more return and then also focusing on developing and increasing the market of those stores that are bringing in less revenue in return.

